"""AI prompt helpers for GameEngineExportWB JSON exchange.

Name: core/json_ai.py
Purpose: build reusable copy/paste prompts that accompany Quick Example JSON when working with an external AI assistant.
Main behavior: returns plain text only; the JSON payload remains unchanged and can still be imported independently.
Modification notes: keep this module independent from FreeCAD, FreeCADGui and Qt; do not rename the stable JSON keys used by the importer.
Version: 2026-08-21-ai-json-prompt-v1
Date and time: 2026-08-21 07:49 -06:00
"""

from __future__ import annotations

import json
from typing import Any


PROMPT_ES = """PROMPT SUGERIDO PARA IA - GAME ENGINE EXPORT WB

Voy a pegar un JSON generado por GameEngineExportWB de FreeCAD. Quiero que me ayude a modificar el ejemplo arquitectonico o laberinto descrito por ese JSON.

Reglas para su respuesta:
- Mantenga la raiz como un objeto JSON valido.
- Mantenga `units` en `mm`.
- Puede modificar `building_type`, `building_variant`, `dimensions`, `terrain`, `segments`, `rooms`, `maze` y `ai_editing` cuando corresponda.
- Para reconstruir el modelo, GameEngineExportWB usa principalmente `dimensions`, `terrain`, `segments` y `rooms`.
- `objects` describe objetos del documento FreeCAD anterior; no lo use como fuente geometrica obligatoria ni invente referencias de objetos.
- Cada segmento debe conservar el formato `[x1, y1, x2, y2]`.
- Mantenga la geometria coherente: muros conectados, puertas y ventanas sobre muros y dimensiones razonables.
- En laberintos, mantenga al menos una entrada y una salida y corredores conectados.
- Devuelva al final un unico objeto JSON completo y valido. No omita campos necesarios para reconstruir el ejemplo.

Antes de devolver el JSON, aplique exactamente los cambios que yo le solicite en lenguaje natural.
"""

PROMPT_EN = """SUGGESTED AI PROMPT - GAME ENGINE EXPORT WB

I will paste JSON generated by the GameEngineExportWB FreeCAD Workbench. Help me modify the architectural or maze example described by this JSON.

Rules for your response:
- Keep the root as one valid JSON object.
- Keep `units` as `mm`.
- You may edit `building_type`, `building_variant`, `dimensions`, `terrain`, `segments`, `rooms`, `maze`, and `ai_editing` when applicable.
- GameEngineExportWB mainly uses `dimensions`, `terrain`, `segments`, and `rooms` to rebuild the model.
- `objects` describes objects from the previous FreeCAD document; do not treat it as mandatory geometry and do not invent object references.
- Every segment must keep the `[x1, y1, x2, y2]` format.
- Keep geometry coherent: connected walls, doors and windows placed on walls, and reasonable dimensions.
- For mazes, keep at least one entrance and one exit and preserve connected corridors.
- Return one complete valid JSON object at the end. Do not omit fields required to rebuild the example.

Before returning the JSON, apply exactly the changes I request in natural language.
"""


def normalize_language(language: str | None) -> str:
    """Return the compact supported language code used by the prompt helper."""
    return "es" if str(language or "es").lower().startswith("es") else "en"


def get_prompt_template(language: str | None = None) -> str:
    """Return the reusable prompt without a JSON payload."""
    return PROMPT_ES if normalize_language(language) == "es" else PROMPT_EN


def _json_text(value: Any) -> str:
    """Return a stable textual JSON representation when a dict/list is provided."""
    if isinstance(value, (dict, list)):
        return json.dumps(value, ensure_ascii=False, indent=2)
    return str(value or "").strip()


def build_ai_prompt(context_json: Any = "", language: str | None = None) -> str:
    """Return the prompt followed by the current JSON context when available."""
    prompt = get_prompt_template(language).rstrip()
    context = _json_text(context_json)
    if not context:
        return prompt + "\n"
    heading = "JSON ACTUAL:" if normalize_language(language) == "es" else "CURRENT JSON:"
    return prompt + "\n\n" + heading + "\n" + context + "\n"


__all__ = [
    "build_ai_prompt",
    "get_prompt_template",
    "normalize_language",
]
