"""Document builder and idempotent updater for service platform fronts."""

from __future__ import annotations

import FreeCAD
import Part

from ...core.naming import safe_name
from ...core.project_structure import msg, set_prop
from .calculator import calculate_layout, position_origins
from .compact_builder import COMPACT_MODE, create_compact_platform, update_compact_platform
from .properties import (
    GENERATED_BY,
    MODULE_TYPE,
    PROPERTY_GROUP,
    read_parameter_sheet,
    set_root_properties,
    tag_representation,
    write_parameter_sheet,
)
from .sketches import create_master_sketches
from .validation import PlatformValidationError, normalize_options


ROOT_BASE_NAME = "FA_ServicePlatformFront"


def create_service_platform_from_axis(doc, axis_reference, values=None):
    """Create the compact workflow while retaining the legacy API below."""
    return create_compact_platform(doc, axis_reference, values)


def create_service_platform_front(doc, values=None):
    """Create a new module, its parameter sheet and all representations."""
    options = normalize_options(values)
    layout = calculate_layout(options)
    msg("Creating service platform front")
    root = doc.addObject("App::DocumentObjectGroup", _unique_name(doc, ROOT_BASE_NAME))
    root.Label = _unique_label(doc, "FA_ServicePlatformFront", exclude=root)

    params_group = _new_group(doc, root, root.Name + "_Parameters", "00_Parameters", "parameters")
    sketches_group = _new_group(doc, root, root.Name + "_MasterSketches", "01_MasterSketches", "master_sketches")
    geometry_group = _new_group(doc, root, root.Name + "_Geometry", "02_Geometry", "geometry")
    metadata_group = _new_group(doc, root, root.Name + "_Metadata", "03_Metadata", "metadata")

    sheet = doc.addObject("Spreadsheet::Sheet", _unique_name(doc, "Spreadsheet_Platform"))
    sheet.Label = _unique_label(doc, "Spreadsheet_Platform", exclude=sheet)
    params_group.addObject(sheet)
    write_parameter_sheet(sheet, options)

    context = doc.addObject("App::FeaturePython", _unique_name(doc, "PA_Context"))
    context.Label = "PA_Context"
    metadata_group.addObject(context)
    set_prop(context, "App::PropertyLinkHidden", "Owner", PROPERTY_GROUP, "Modulo propietario", root)
    set_prop(context, "App::PropertyLink", "ParameterSheet", PROPERTY_GROUP, "Parametros", sheet)
    set_prop(context, "App::PropertyString", "FA_ModuleType", PROPERTY_GROUP, "Tipo", MODULE_TYPE)

    _link_groups(root, params_group, sketches_group, geometry_group, metadata_group, context)
    set_root_properties(root, options, layout, sheet)
    result = _generate(doc, root, sketches_group, geometry_group, options, layout)
    result.update({"root": root, "sheet": sheet, "context": context, "layout": layout})
    _print_summary(options, layout, result)
    return result


def update_service_platform_front(doc, root):
    """Rebuild only representations generated by this module."""
    root = find_platform_root(root)
    if root is None:
        raise PlatformValidationError("Seleccione un grupo FA_ServicePlatformFront valido.")
    if str(getattr(root, "FA_GenerationMode", "") or "") == COMPACT_MODE:
        return update_compact_platform(doc, root)
    sheet = getattr(root, "FA_ParameterSheet", None)
    if sheet is None:
        raise PlatformValidationError("El modulo seleccionado no conserva su Spreadsheet_Platform.")
    options = read_parameter_sheet(sheet)
    layout = calculate_layout(options)
    msg("Updating service platform front")
    sketches_group = getattr(root, "FA_MasterSketchesGroup", None)
    geometry_group = getattr(root, "FA_GeometryGroup", None)
    if sketches_group is None or geometry_group is None:
        raise PlatformValidationError("El modulo no conserva sus grupos maestros de sketches y geometria.")
    removed = remove_generated_representations(doc, sketches_group, geometry_group)
    set_root_properties(root, options, layout, sheet)
    result = _generate(doc, root, sketches_group, geometry_group, options, layout)
    result.update({"root": root, "sheet": sheet, "layout": layout, "removed": removed})
    msg("Representaciones anteriores eliminadas: %d" % removed)
    _print_summary(options, layout, result)
    return result


def find_platform_root(obj):
    """Resolve the semantic owner from a selected root or representation."""
    if obj is None:
        return None
    if str(getattr(obj, "FA_ModuleType", "")) == MODULE_TYPE and hasattr(obj, "FA_ParameterSheet"):
        return obj
    owner = getattr(obj, "Owner", None)
    if owner is not None and str(getattr(owner, "FA_ModuleType", "")) == MODULE_TYPE:
        return owner
    pending = list(getattr(obj, "InList", []) or [])
    seen = set()
    while pending:
        candidate = pending.pop(0)
        name = str(getattr(candidate, "Name", ""))
        if name in seen:
            continue
        seen.add(name)
        if str(getattr(candidate, "FA_ModuleType", "")) == MODULE_TYPE and hasattr(
            candidate, "FA_ParameterSheet"
        ):
            return candidate
        pending.extend(list(getattr(candidate, "InList", []) or []))
    return None


def remove_generated_representations(doc, sketches_group, geometry_group):
    """Remove only objects tagged by this generator; preserve user additions and groups."""
    candidates = []
    for group in (sketches_group, geometry_group):
        for obj in _descendants(group):
            if str(getattr(obj, "FA_GeneratedBy", "")) == GENERATED_BY:
                candidates.append(obj)
    count = 0
    for obj in reversed(candidates):
        try:
            if doc.getObject(obj.Name) is not None:
                doc.removeObject(obj.Name)
                count += 1
        except Exception:
            pass
    return count


def _generate(doc, root, sketches_group, geometry_group, options, layout):
    sketches = create_master_sketches(doc, sketches_group, root, options, layout)
    subgroups = _ensure_geometry_groups(doc, geometry_group, root)
    geometry = _create_geometry(doc, subgroups, root, options, layout)
    return {"sketches": sketches, "geometry": geometry, "geometry_groups": subgroups}


def _create_geometry(doc, groups, root, options, layout):
    created = {"desks": [], "dividers": [], "staff_zones": [], "public_zones": []}
    origins = position_origins(options, layout)
    y0 = options.front_offset_mm
    if options.create_3d_furniture:
        for index, x in enumerate(origins, start=1):
            desk = _box(
                doc,
                groups["desks"],
                "%s__PA_Desk_%02d" % (root.Name, index),
                "PA_Desk_%02d" % index,
                layout.position_width_mm,
                options.desk_depth_mm,
                options.desk_thickness_mm,
                (x, y0, options.desk_height_mm - options.desk_thickness_mm),
                root,
                "desk",
                (0.72, 0.46, 0.24),
            )
            created["desks"].append(desk)
        for index in range(layout.divider_count):
            x = origins[index] + layout.position_width_mm
            divider = _box(
                doc,
                groups["dividers"],
                "%s__PA_Divider_%02d" % (root.Name, index + 1),
                "PA_Divider_%02d" % (index + 1),
                options.divider_thickness_mm,
                options.divider_depth_mm,
                options.divider_height_mm,
                (x, y0, options.desk_height_mm),
                root,
                "divider",
                (0.55, 0.55, 0.58),
            )
            created["dividers"].append(divider)
    if options.create_functional_zones:
        for index, x in enumerate(origins, start=1):
            staff = _box(
                doc,
                groups["staff_zones"],
                "%s__PA_StaffZone_%02d" % (root.Name, index),
                "PA_StaffZone_%02d" % index,
                layout.position_width_mm,
                options.staff_zone_depth_mm,
                10.0,
                (x, y0 + options.desk_depth_mm, 0.0),
                root,
                "staff_zone",
                (0.25, 0.75, 0.30),
                transparency=80,
            )
            public = _box(
                doc,
                groups["public_zones"],
                "%s__PA_PublicZone_%02d" % (root.Name, index),
                "PA_PublicZone_%02d" % index,
                layout.position_width_mm,
                options.public_zone_depth_mm,
                10.0,
                (x, y0 - options.public_zone_depth_mm, 0.0),
                root,
                "public_zone",
                (0.25, 0.45, 0.90),
                transparency=80,
            )
            created["staff_zones"].append(staff)
            created["public_zones"].append(public)
    return created


def _box(doc, group, name, label, length, depth, height, base, owner, part, color, transparency=0):
    obj = doc.addObject("Part::Feature", name)
    obj.Label = label
    obj.Shape = Part.makeBox(
        float(length), float(depth), float(height), FreeCAD.Vector(*[float(value) for value in base])
    )
    group.addObject(obj)
    tag_representation(obj, owner, "Model" if "zone" not in part else "Analysis", part)
    try:
        obj.ViewObject.ShapeColor = color
        obj.ViewObject.Transparency = int(transparency)
    except Exception:
        pass
    return obj


def _ensure_geometry_groups(doc, geometry_group, root):
    specs = (
        ("desks", "PA_Desks"),
        ("dividers", "PA_Dividers"),
        ("staff_zones", "PA_StaffZones"),
        ("public_zones", "PA_PublicZones"),
    )
    result = {}
    existing = list(getattr(geometry_group, "Group", []) or [])
    for key, label in specs:
        group = next((obj for obj in existing if str(getattr(obj, "Label", "")) == label), None)
        if group is None:
            group = _new_group(doc, geometry_group, root.Name + "_" + label, label, key)
        result[key] = group
    return result


def _new_group(doc, parent, name, label, role):
    group = doc.addObject("App::DocumentObjectGroup", _unique_name(doc, name))
    group.Label = label
    parent.addObject(group)
    set_prop(group, "App::PropertyString", "FA_Role", PROPERTY_GROUP, "Rol", role)
    return group


def _link_groups(root, params, sketches, geometry, metadata, context):
    links = (
        ("FA_ParametersGroup", params),
        ("FA_MasterSketchesGroup", sketches),
        ("FA_GeometryGroup", geometry),
        ("FA_MetadataGroup", metadata),
        ("FA_Context", context),
    )
    for name, obj in links:
        set_prop(root, "App::PropertyLink", name, PROPERTY_GROUP, "Estructura del modulo", obj)


def _descendants(group):
    pending = list(getattr(group, "Group", []) or [])
    seen = set()
    result = []
    while pending:
        obj = pending.pop(0)
        name = str(getattr(obj, "Name", ""))
        if not name or name in seen:
            continue
        seen.add(name)
        result.append(obj)
        pending.extend(list(getattr(obj, "Group", []) or []))
    return result


def _unique_name(doc, base):
    base = safe_name(base)
    if doc.getObject(base) is None:
        return base
    index = 2
    while doc.getObject("%s_%03d" % (base, index)) is not None:
        index += 1
    return "%s_%03d" % (base, index)


def _unique_label(doc, base, exclude=None):
    labels = {str(getattr(obj, "Label", "")) for obj in doc.Objects if obj is not exclude}
    if base not in labels:
        return base
    index = 2
    while "%s %d" % (base, index) in labels:
        index += 1
    return "%s %d" % (base, index)


def _print_summary(options, layout, result):
    geometry = result["geometry"]
    msg("Total width: %.1f mm" % options.total_width_mm)
    msg("Service positions: %d" % options.service_positions)
    msg("Calculated position width: %.1f mm" % layout.position_width_mm)
    msg("Master sketches created: %d" % len(result["sketches"]))
    msg("Desk solids created: %d" % len(geometry["desks"]))
    msg("Divider solids created: %d" % len(geometry["dividers"]))
    msg("Service platform front completed")
